
import javax.swing.JDialog;
import javax.swing.*;
import javax.swing.table.*;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author developer
 */
public class WindowOne extends javax.swing.JFrame {

    /**
     * Creates new form WindowOne
     */
    public WindowOne() {
        Object[] columns = {"ID", "First Name", "Last Name", "Age"};
        Object[][] rows = {
            {"1", "AAAA", "BBBB", "11"},
            {"2", "AAAA", "BBBB", "22"},
            {"3", "AAAA", "BBBB", "33"},
            {"4", "AAAA", "BBBB", "44"},
            {"5", "AAAA", "BBBB", "55"},
            {"6", "AAAA", "BBBB", "66"},
            {"7", "AAAA", "BBBB", "11"},
            {"8", "AAAA", "BBBB", "11"},
            {"9", "AAAA", "BBBB", "11"},
            {"10", "AAAA", "BBBB", "11"},
            {"11", "AAAA", "BBBB", "11"},
            {"12", "AAAA", "BBBB", "11"},
            {"13", "AAAA", "BBBB", "11"},
            {"14", "AAAA", "BBBB", "11"},
            {"15", "AAAA", "BBBB", "11"},
            {"16", "AAAA", "BBBB", "11"}
        };
        DefaultTableModel model = new DefaultTableModel();
        model.setDataVector(rows, columns);

        //JTable table = new JTable();
        sysTblOne = new JTable(model);
        sysScrollPanel = new JScrollPane(sysTblOne);
        getContentPane().add(sysScrollPanel);
        //sysTblOne.setModel(model);
        initComponents();
        
        
        Object[] row = {"Id", "Name", "Value"};
        DefaultTableModel modelTwo = (DefaultTableModel) sysTblOne.getModel();
        modelTwo.addRow(row);
        
        
        /*sysTblOne = new JTable(new DefaultTableModel());
        String ColsName[] = {"Id", "Name", "Value"};
        DefaultTableModel model = new DefaultTableModel(null, ColsName);

        /-*for (int j = 0; j < 3; j++) { //loop to add 3 rows
            dtm2.addRow(new String[3]);
        }*-/
        model.addRow(new Object[]{"Column 1", "Column 2", "Column 3"});
        model.addColumn("Name");
        sysTblOne.setModel(model); // Set model of the table to Default Table Model
        sysTblOne.getModel().setValueAt("1", 0, 0);
        model.insertRow(0, new Object[]{"r1", "r2", "r3"});*/
        //sysTblOne = new JTable(model);
        //sysTblOne.getModel().setValueAt("2", 1, 0);
        //sysTblOne.getModel().setValueAt("3", 2, 0);

        /*Object[] columns = {"ID", "First Name", "Last Name", "Age"};
        Object[][] rows = {
            {"1", "AAAA", "BBBB", "11"}, {"2", "AAAA", "BBBB", "22"},
            {"3", "AAAA", "BBBB", "33"}, {"4", "AAAA", "BBBB", "44"},
            {"5", "AAAA", "BBBB", "55"}, {"6", "AAAA", "BBBB", "66"},
            {"7", "AAAA", "BBBB", "11"}, {"8", "AAAA", "BBBB", "11"},
            {"9", "AAAA", "BBBB", "11"}, {"10", "AAAA", "BBBB", "11"},
            {"11", "AAAA", "BBBB", "11"}, {"12", "AAAA", "BBBB", "11"},
            {"13", "AAAA", "BBBB", "11"}, {"14", "AAAA", "BBBB", "11"},
            {"15", "AAAA", "BBBB", "11"}, {"16", "AAAA", "BBBB", "11"}
        };
        DefaultTableModel model = new DefaultTableModel();
        model.setDataVector(rows, columns);

        //JTable table = new JTable();
        sysTblOne = new JTable();
        sysTblOne.setModel(model);
        jScrollPane1 = new JScrollPane(sysTblOne);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sysBtnOne = new javax.swing.JButton();
        sysTxtOne = new javax.swing.JTextField();
        sysScrollPanel = new javax.swing.JScrollPane();
        sysTblOne = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sysBtnOne.setText("Button One");
        sysBtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sysBtnOneActionPerformed(evt);
            }
        });

        sysTblOne.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sysScrollPanel.setViewportView(sysTblOne);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sysBtnOne)
                        .addGap(0, 274, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sysTxtOne)
                            .addComponent(sysScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sysBtnOne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sysTxtOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sysScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sysBtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sysBtnOneActionPerformed
        // TODO add your handling code here:
        System.out.println("Hello, why you clicked me " + sysTxtOne.getText());
        /*JDialog d = new JDialog(this, "Hello", true);
        d.setLocationRelativeTo(this);
        d.setVisible(true);*/
        Object[] row = {"Id", "Name", "Value"};
        DefaultTableModel model = (DefaultTableModel) sysTblOne.getModel();
        model.addRow(row);

        /*DefaultTableModel modelTwo = new DefaultTableModel();
        List<String> list = new ArrayList<String>();
        list.add("1");
        list.add("Name-1");
        list.add("Value-1");
        modelTwo.addRow(list.toArray());
        sysTblOne.setModel(modelTwo);*/
        
        List<String> list = new ArrayList<String>();
        list.add("1");
        list.add("Name-1");
        list.add("Value-1");
        DefaultTableModel modelTwo = (DefaultTableModel) sysTblOne.getModel();
        model.addRow(list.toArray());
    }//GEN-LAST:event_sysBtnOneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowOne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WindowOne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton sysBtnOne;
    private javax.swing.JScrollPane sysScrollPanel;
    private javax.swing.JTable sysTblOne;
    private javax.swing.JTextField sysTxtOne;
    // End of variables declaration//GEN-END:variables
}
/*
https://stackoverflow.com/questions/13851788/why-cant-i-use-defaulttablemodel-am-i-missing-something-obvious-java
https://www.beginnersheap.com/create-use-java-table-netbeans/
https://www.experts-exchange.com/questions/27439053/Delete-Rows-in-JTable-Netbeans-Java-MySQL.html
http://www.java2s.com/Code/Java/Swing-JFC/CreatingsimpleJTableusingAbstractTableModel.htm


https://stackoverflow.com/questions/21135452/how-to-add-row-of-data-to-jtable-from-values-received-from-jtextfield-and-combob

 */
